name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: (env) setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.35'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: (env) cache
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: (env) globals
        run: bun add -g oxlint

      - run: bun install
      - run: oxlint .
      - run: bun run build
      - run: bun run typecheck
      - run: bun test
      
      - run: pip install -r ./validation/requirements.txt
      - name: w3c validation test
        run: ./validation/test.sh

  test_rs:
    name: Rust ${{ matrix.rustv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rustv: [nightly, stable]
    defaults:
      run:
        working-directory: ./cargo
    steps:
      - uses: actions/checkout@main

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rustv }}

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - run: cargo fmt --all -- --check
      - run: cargo test --all-features
      - run: cargo build --release
