name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: (env) setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.18

      - name: (env) cache
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: (env) globals
        run: bun add -g oxlint

      - run: bun install
      - run: oxlint .
      - run: bun run build
      - run: bun run typecheck
      - run: bun test

  test_rs:
    name: Rust ${{ matrix.rustv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rustv: [nightly, stable]
    steps:
      - uses: actions/checkout@main

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rustv }}

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
