name: Rust

on:
  push:
  workflow_call:

jobs:
  test:
    name: Rust ${{ matrix.rustv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rustv: [nightly, stable]
    defaults:
      run:
        working-directory: ./cargo
    steps:
      - uses: actions/checkout@main

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rustv }}

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - run: cargo fmt --all -- --check
      - run: cargo test --all-features
      - run: cargo build --release
