name: Rust

on:
  push:
    paths: ['.github/**', '.cargo/**']

jobs:
  test:
    name: test ${{ matrix.rustv }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rustv: [nightly, stable]
    defaults:
      run:
        working-directory: ./cargo
    steps:
      - uses: actions/checkout@v4

      - run: rustup set profile minimal
      - run: rustup default ${{ matrix.rustv }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci-test-${{ matrix.os }}-${{ matrix.rustv }}

      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo test --all-features
      - run: cargo build --release
